name: Frontend Cypress Tests

on: [push]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
